version: 0.4.{build}

environment:
  matrix:
    - nodejs_version: 8.11.3
      POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6

platform:
  - x64

services:
  - postgresql96

cache:
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%


install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install --force

build_script:
  - yarn run build
  - yarn run pack

after_build:
        - ps: |
            $FALCON_VERSION = node -p "require('./package.json').version"
            cd release
            7z a win-falcon-v$FALCON_VERSION.zip *.exe

artifacts:
  - path: release\*.zip

test: off
